name: atlas_python
channels:
  - defaults
dependencies:
  - numpy = 1.18.5
  - scipy = 1.7.1
  - scikit-learn = 1.0.1
  - matplotlib = 3.4.3
  - seaborn = 0.11.2
  - pip:
    - watermark = 2.2.0
    - blackcellmagic = 0.0.3
